app/models.py
__author__ = 'vitor'

import datetime
import os
from flask.globals import current_app
from werkzeug.utils import secure_filename
from app import db
from sqlalchemy.sql.schema import Column
from sqlalchemy.sql.sqltypes import Integer, String, Date


class Image(db.Model):
    __tablename__ = 'images'
    id = Column(Integer, primary_key=True)
    name = Column(String(255), unique=True, nullable=False)
    image_path = Column(String(255), unique=True, nullable=False)
    created_at = Column(Date, default=datetime.datetime.now())
    updated_at = Column(Date, onupdate=datetime.datetime.now())

    def save(self, file):
        if file and Image.allowed_image(file.filename):
            filename = secure_filename(file.filename)
            try:
                path = os.path.join(current_app.config['IMAGES_UPLOAD_FOLDER'], filename)
                self.name = filename
                self.image_path = path
                db.session.add(self)

                file.save(path)
            except Exception as e:
                raise e

    @staticmethod
    def allowed_image(filename):
        return '.' in filename and \
            filename.rsplit('.', 1)[1] in current_app.config.get('IMAGE_ALLOWED_EXTENSIONS')

app/__init__.py
from flask import Flask
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy
from config import config


bootstrap = Bootstrap()
db = SQLAlchemy()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # attach routes and custom error pages here
    return app

app/main/__init__.py
__author__ = 'vitor'

from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
__author__ = 'vitor'

from app.models import Image
from flask.globals import request
from flask import render_template
from . import main


@main.route('/', methods=['GET', 'POST'])
def upload_image():
    if request.method == 'POST':
        file = request.files.getlist('file')
        image = Image()
        image.save(file[0])
    return render_template('upload.html')

app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}Flask Jquery-File-Upload Example{% endblock %}

{% block head %}
    {{ super() }}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
     <style>
        body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
        }
    </style>
    {% block scripts %}
        {{ super() }}
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
            <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
    {% endblock %}
{% endblock %}


{% block body %}
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                <a class="navbar-brand" href="#">Flask + JQuery File Upload + Bootstrap</a>
                </div>
            </div>
            <!-- /.container -->
        </nav>

        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">

                    <p class="lead">Image upload example</p>
                    {% block page_content %} {% endblock %}
                </div>
            </div>
          <!-- /.row -->
        </div>
    </body>
{% endblock %}

app/templates/upload.html
{% extends "base.html" %}

{% block head %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename = 'js/jquery-file-upload/css/jquery.fileupload.css') }}">
    {%  block scripts %}
        {{ super() }}

        <script src="//blueimp.github.io/JavaScript-Load-Image/js/load-image.all.min.js"></script>


        <script src="{{ url_for('static', filename = 'js/jquery-file-upload/js/vendor/jquery.ui.widget.js') }}"></script>
        <script src="{{ url_for('static', filename = 'js/javascript-templates/tmpl.min.js') }}"></script>
        <script src="{{ url_for('static', filename = 'js/jquery-file-upload/js/jquery.iframe-transport.js') }}"></script>
        <script src="{{ url_for('static', filename = 'js/jquery-file-upload/js/jquery.fileupload.js') }}"></script>
        <script src="{{ url_for('static', filename = 'js/jquery-file-upload/js/jquery.fileupload-process.js') }}"></script>
        <script src="{{ url_for('static', filename = 'js/jquery-file-upload/js/jquery.fileupload-image.js') }}"></script>
        <script src="{{ url_for('static', filename = 'js/jquery-file-upload/js/jquery.fileupload-validate.js') }}"></script>
        <script src="{{ url_for('static', filename = 'js/jquery-file-upload/js/jquery.fileupload-ui.js') }}"></script>

        <script>
            $(function () {
                {# Get your upload form by ID #}
                $('#fileupload_form').fileupload({
                    url: "{{ url_for('main.upload_image') }}",
                    downloadTemplateId: null {# if null by default search script with id='template-upload' #}
                });
            });
        </script>
        {# Javascript Template used by JQuery File Upload.#}
        <script id="template-upload" type="text/x-tmpl">
            {% raw %}
            {% for (var i=0, file; file=o.files[i]; i++) { %}
                <tr class="template-upload fade" >
                    <td>
                        <span class="preview"></span>
                    </td>
                    <td style="max-width: 20%">
                        <p class="name">{%=file.name%}</p>
                        <strong class="error text-danger"></strong>
                    </td>
                    <td>
                        <p class="size">Processing</p>
                        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
                    </td>
                    <td>
                        {% if (!i && !o.options.autoUpload) { %}
                            <button class="btn btn-primary start" disabled>
                                <i class="glyphicon glyphicon-upload"></i>
                                <span>Send</span>
                            </button>
                        {% } %}
                        {% if (!i) { %}
                            <button class="btn btn-warning cancel">
                                <i class="glyphicon glyphicon-ban-circle"></i>
                                <span>Cancel</span>
                            </button>
                        {% } %}
                    </td>
                </tr>
            {% } %}
            {% endraw %}
        </script>
    {% endblock %}
{% endblock %}


{% block page_content %}
<form id="fileupload_form" method="POST" action="{{ url_for('main.upload_image') }}" enctype="multipart/form-data">
    <!-- Redirect browsers with JavaScript disabled to the origin page -->
    <div class="box-header with-border">
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="col-lg-5">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn btn-success fileinput-button">
                    <i class="glyphicon glyphicon-plus"></i>
                    <span>Add images</span>
                    <input  type="file"  name="file" multiple>
                </span>
                <button type="submit" class="btn btn-primary start">
                    <i class="glyphicon glyphicon-upload"></i>
                    <span>Send</span>
                </button>
                <button type="reset" class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            </div>
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"></div>
                </div>
                <!-- The extended global progress state -->
                <div class="progress-extended">&nbsp;</div>
            </div>
        </div>
    </div>
    <div class="box-body">
        <!-- The table listing the files available for upload -->
        <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
    </div>
</form>
{% endblock %}